"""8

Revision ID: 0c9369dac7ba
Revises: ea99aaa53ab9
Create Date: 2022-09-14 13:07:21.630963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c9369dac7ba'
down_revision = 'ea99aaa53ab9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
