"""second

Revision ID: 3ed6a321f770
Revises: a027c9cef82d
Create Date: 2022-09-14 12:54:40.619364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ed6a321f770'
down_revision = 'a027c9cef82d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
