"""5

Revision ID: ae46f73fff8f
Revises: b0c8514aefbe
Create Date: 2022-09-14 13:00:56.031402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae46f73fff8f'
down_revision = 'b0c8514aefbe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
