"""4

Revision ID: b0c8514aefbe
Revises: ef93a3ed33c9
Create Date: 2022-09-14 12:59:28.379872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0c8514aefbe'
down_revision = 'ef93a3ed33c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
