"""6

Revision ID: e5c90bb32af9
Revises: ae46f73fff8f
Create Date: 2022-09-14 13:03:28.255277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5c90bb32af9'
down_revision = 'ae46f73fff8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
