"""7

Revision ID: ea99aaa53ab9
Revises: e5c90bb32af9
Create Date: 2022-09-14 13:04:06.382600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea99aaa53ab9'
down_revision = 'e5c90bb32af9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
