"""3

Revision ID: ef93a3ed33c9
Revises: 3ed6a321f770
Create Date: 2022-09-14 12:57:12.186831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef93a3ed33c9'
down_revision = '3ed6a321f770'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
